"""Core contracts, configuration, registry and utilities."""

from core.config import AppConfig, Paths, load_config
from core.errors import (
    AudioError,
    BackendTimeout,
    BackendUnavailable,
    BadRequest,
    ChatBotError,
    Conflict,
    NotFound,
    Unsupported,
    UpstreamError,
)
from core.logging import get_logger, setup_logging
from core.registry import Registry, get_registry, register, registry
from core.types import (
    AudioClip,
    Completion,
    Embedder,
    LLMBackend,
    LLMRequest,
    LLMStats,
    MemoryHit,
    MemoryItem,
    MemoryKind,
    Message,
    Persona,
    Reranker,
    RetrievalQuery,
    RetrievalResult,
    Role,
    SpeechChunk,
    STTBackend,
    TokenEvent,
    Transcript,
    TTSBackend,
    VectorStore,
    VoiceSpec,
    new_id,
    now_ts,
)

__all__ = [
    "AppConfig",
    "AudioClip",
    "BackendTimeout",
    "BackendUnavailable",
    "BadRequest",
    "ChatBotError",
    "Completion",
    "Conflict",
    "Embedder",
    "LLMBackend",
    "LLMRequest",
    "LLMStats",
    "MemoryHit",
    "MemoryItem",
    "MemoryKind",
    "Message",
    "NotFound",
    "Paths",
    "Persona",
    "Registry",
    "Reranker",
    "RetrievalQuery",
    "RetrievalResult",
    "Role",
    "STTBackend",
    "SpeechChunk",
    "TTSBackend",
    "TokenEvent",
    "Transcript",
    "Unsupported",
    "UpstreamError",
    "VectorStore",
    "VoiceSpec",
    "get_logger",
    "get_registry",
    "load_config",
    "new_id",
    "now_ts",
    "register",
    "registry",
    "setup_logging",
]
